# -*- coding: utf-8 -*-

RUSSIAN_TO_INTERNAL_BIAS_MAP = {
    # Сопоставление русских названий из COGNITIVE_BIASES с внутренними ключами системы
    "Черно-белое мышление (Дихотомическое мышление)": "black_and_white_thinking",
    "Сверхобобщение": "overgeneralization",
    "Катастрофизация": "catastrophizing",
    "Чтение мыслей": "mind_reading",
    "Персонализация": "personalization",
    "Ошибка ретроспективного взгляда ('Я так и знал')": "hindsight_bias",
    "Эмоциональное обоснование": "emotional_reasoning",
    "Эвристика доступности": "availability_heuristic",
    "Отклонение в сторону статуса кво": "status_quo_bias",
    "Ошибка игрока": "gamblers_fallacy",
    "Систематическая ошибка выживаемости": "survivorship_bias",
    "Эффект ложного консенсуса": "false_consensus_effect",
    "Эффект ореола (гало-эффект)": "halo_effect",
    # Добавляем другие искажения из библиотеки, даже если они пока не используются в логике Оркестратора
    "Эмоциональный разрыв": "empathy_gap",
    "Отклонение в сторону позитивного исхода": "valence_effect",
    "Каскад доступной информации (эффект мнимой правды)": "availability_cascade",
    "Отрицание вероятности": "neglect_of_probability",
    "Предвзятость подтверждения": "confirmation_bias",
    "Эффект повального увлечения": "bandwagon_effect",
    "Эффект фокусировки": "focusing_effect",
    "Выборочное восприятие": "selective_perception",
    "Самосбывающееся пророчество": "self_fulfilling_prophecy",
    "Иллюзорная корреляция": "illusory_correlation",
    "Искажение, вызванное пессимизмом": "pessimism_bias",
    "Искажение, вызванное оптимизмом": "optimism_bias",
    "Эффект неоднозначности": "ambiguity_effect",
    "Эффект привязки (эффект якоря)": "anchoring",
    "Искажение, вызванное вниманием": "attentional_bias",
    "Эффект обратной вспышки": "backfire_effect",
    "Ошибка базовой доли (ошибка, связанная с частными примерами)": "base_rate_fallacy",
    "Искажение, вызванное верой": "belief_bias",
    "Мертвая зона когнитивных искажений (слепое пятно в отношении когнитивных искажений)": "bias_blind_spot",
    "Искажение, поддерживающее выбор": "choice_supportive_bias",
    "Иллюзия кластеризации": "clustering_illusion",
    "Проклятие знания": "curse_of_knowledge",
    "Гипотеза «справедливого мира»": "just_world_hypothesis"
}
